//! bridge-core — shared types and the canonical cross-chain hashing.
//!
//! THE HASH IS SACRED. [`submission_id`] / [`submission_id_with_auto`] must
//! reproduce, byte-for-byte, the Solidity `BridgeHash` library used by the Gate
//! contract. The Phase-3 equivalence test (`tests/equivalence.rs`) locks this in
//! against fixtures generated by Foundry.

use alloy_primitives::{keccak256, Address, B256, U256};

mod submission;
pub use submission::Submission;

pub mod allow;
pub mod config;
/// Block-window arithmetic shared by the validator and indexer scanners.
pub mod scan;
pub mod store;

#[cfg(feature = "abi")]
pub mod abi;

// Key custody for the relayer nodes. Needs alloy's local signer / keystore, so
// it rides the same `abi` feature the validator and keeper already enable.
#[cfg(feature = "abi")]
pub mod signer;

#[cfg(feature = "http")]
pub mod remote;

// The shared read/write view over the signature store (file dir or the HTTP
// sig-store), used by the validator, keeper and GraphQL API alike. Needs both
// the `http` client and the `abi` trust-boundary checks the file path runs.
#[cfg(all(feature = "http", feature = "abi"))]
pub mod backend;

#[cfg(feature = "axum-auth")]
pub mod auth;

/// Per-credential rate limiting for the same HTTP surfaces `auth` guards. Shares
/// the `axum-auth` feature because it is the same dependency and the same layer.
#[cfg(feature = "axum-auth")]
pub mod ratelimit;

/// Domain-separating prefix, matching `BridgeHash.SUBMISSION_PREFIX` in Solidity.
pub const SUBMISSION_PREFIX: u64 = 1;
/// Prefix for a destination-side CANCEL attestation (`BridgeHash.CANCEL_PREFIX`).
pub const CANCEL_PREFIX: u64 = 2;
/// Prefix for a source-side REFUND attestation (`BridgeHash.REFUND_PREFIX`).
pub const REFUND_PREFIX: u64 = 3;

/// Optional execution payload attached to a transfer.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct AutoParams {
    pub execution_fee: U256,
    pub flags: U256,
    pub fallback_address: Vec<u8>,
    pub data: Vec<u8>,
    /// Packed source-chain sender (20 bytes for an EVM address).
    pub native_sender: Vec<u8>,
}

/// `debridgeId = keccak256(abi.encodePacked(nativeChainId, nativeToken))`.
pub fn debridge_id(native_chain_id: U256, native_token: Address) -> B256 {
    let mut packed = Vec::with_capacity(32 + 20);
    packed.extend_from_slice(&native_chain_id.to_be_bytes::<32>());
    packed.extend_from_slice(native_token.as_slice());
    keccak256(packed)
}

/// The 9-field packed base of every submissionId (unhashed), matching
/// `BridgeHash.packedSubmission`.
///
/// `bridge_domain` identifies the DEPLOYMENT GENERATION and must equal the
/// `bridgeDomain()` of the gates this id will be presented to. It exists because
/// without it a submissionId commits to no contract identity at all, so a quorum
/// signature from a superseded deployment verifies perfectly against a freshly
/// deployed gate (which also restarts its nonces). See `Gate.bridgeDomain`.
///
/// `bridge_decimals` is the WIRE SCALE `amount` is denominated in (H-2). `amount`
/// is a bare integer whose meaning is entirely decided by what each gate
/// registered for the asset; leaving the scale out made the two ends agreeing a
/// convention rather than a check, and a one-digit mis-registration then paid out
/// a power of ten on an ordinary transfer. Each gate hashes ITS OWN registration,
/// so a mismatch yields two ids that never meet. One byte, packed between two
/// 32-byte words.
fn packed_submission(
    bridge_domain: B256,
    debridge_id: B256,
    bridge_decimals: u8,
    amount: U256,
    chain_id_from: U256,
    chain_id_to: U256,
    nonce: U256,
    receiver: &[u8],
) -> Vec<u8> {
    let mut packed = Vec::with_capacity(32 * 7 + 1 + receiver.len());
    packed.extend_from_slice(&U256::from(SUBMISSION_PREFIX).to_be_bytes::<32>());
    packed.extend_from_slice(bridge_domain.as_slice());
    packed.extend_from_slice(debridge_id.as_slice());
    packed.extend_from_slice(&chain_id_from.to_be_bytes::<32>());
    packed.extend_from_slice(&chain_id_to.to_be_bytes::<32>());
    packed.push(bridge_decimals);
    packed.extend_from_slice(&amount.to_be_bytes::<32>());
    packed.extend_from_slice(receiver);
    packed.extend_from_slice(&nonce.to_be_bytes::<32>());
    packed
}

/// submissionId for a transfer WITHOUT an execution payload.
#[allow(clippy::too_many_arguments)]
pub fn submission_id(
    bridge_domain: B256,
    debridge_id: B256,
    bridge_decimals: u8,
    amount: U256,
    chain_id_from: U256,
    chain_id_to: U256,
    nonce: U256,
    receiver: &[u8],
) -> B256 {
    keccak256(packed_submission(
        bridge_domain,
        debridge_id,
        bridge_decimals,
        amount,
        chain_id_from,
        chain_id_to,
        nonce,
        receiver,
    ))
}

/// submissionId for a transfer WITH an execution payload.
#[allow(clippy::too_many_arguments)]
pub fn submission_id_with_auto(
    bridge_domain: B256,
    debridge_id: B256,
    bridge_decimals: u8,
    amount: U256,
    chain_id_from: U256,
    chain_id_to: U256,
    nonce: U256,
    receiver: &[u8],
    auto: &AutoParams,
) -> B256 {
    let mut packed = packed_submission(
        bridge_domain,
        debridge_id,
        bridge_decimals,
        amount,
        chain_id_from,
        chain_id_to,
        nonce,
        receiver,
    );
    packed.extend_from_slice(&auto.execution_fee.to_be_bytes::<32>());
    packed.extend_from_slice(&auto.flags.to_be_bytes::<32>());
    packed.extend_from_slice(keccak256(&auto.fallback_address).as_slice());
    packed.extend_from_slice(keccak256(&auto.data).as_slice());
    packed.extend_from_slice(keccak256(&auto.native_sender).as_slice());
    keccak256(packed)
}

/// Decode the abi-encoded `autoParams` blob a `Sent` event carries, pairing it
/// with the event's packed `nativeSender` (which rides alongside the blob rather
/// than inside it).
///
/// `Ok(None)` is "no execution payload" (an empty blob). `Err` is "there IS a
/// payload but it does not decode" — a caller must fail closed on that and must
/// never fold it into `None`, because the plain-transfer id and the with-auto id
/// for the same transfer are different hashes.
#[cfg(feature = "abi")]
pub fn decode_auto_params(
    auto_params: &[u8],
    native_sender: &[u8],
) -> Result<Option<AutoParams>, alloy::sol_types::Error> {
    use alloy::sol_types::SolValue;

    if auto_params.is_empty() {
        return Ok(None);
    }
    let ap = abi::AutoParamsTo::abi_decode(auto_params)?;
    Ok(Some(AutoParams {
        execution_fee: ap.executionFee,
        flags: ap.flags,
        fallback_address: ap.fallbackAddress.to_vec(),
        data: ap.data.to_vec(),
        native_sender: native_sender.to_vec(),
    }))
}

/// Digest a validator signs to authorise CANCELLING a transfer on the
/// destination chain — byte-identical to `BridgeHash.getCancelId`.
///
/// The domain prefix (and the 64-byte preimage, against a submissionId's >= 224)
/// is what stops a validator's transfer signature from being replayed as a
/// cancel authorisation. See [`refund_id`] for the source-side counterpart.
pub fn cancel_id(submission_id: B256) -> B256 {
    domain_id(CANCEL_PREFIX, submission_id)
}

/// Digest a validator signs to authorise REFUNDING a cancelled transfer on the
/// source chain — byte-identical to `BridgeHash.getRefundId`.
pub fn refund_id(submission_id: B256) -> B256 {
    domain_id(REFUND_PREFIX, submission_id)
}

/// `keccak256(abi.encodePacked(uint256(prefix), submissionId))`.
fn domain_id(prefix: u64, submission_id: B256) -> B256 {
    let mut packed = Vec::with_capacity(64);
    packed.extend_from_slice(&U256::from(prefix).to_be_bytes::<32>());
    packed.extend_from_slice(submission_id.as_slice());
    keccak256(packed)
}
