//! Phase 3 — cross-language submissionId equivalence.
//!
//! Reads the fixtures generated by Foundry (`forge test --match-contract GenFixtures`)
//! and asserts that the Rust hashing reproduces every Solidity-computed id
//! byte-for-byte. If this ever fails, no validator signature would verify.

use std::path::PathBuf;

use alloy_primitives::{B256, U256};
use bridge_core::{AutoParams, Submission};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Fixtures {
    fixtures: Vec<Fixture>,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    name: String,
    #[serde(rename = "bridgeDomain")]
    bridge_domain: String,
    #[serde(rename = "debridgeId")]
    debridge_id: String,
    #[serde(rename = "bridgeDecimals")]
    bridge_decimals: u8,
    amount: String,
    #[serde(rename = "chainIdFrom")]
    chain_id_from: u64,
    #[serde(rename = "chainIdTo")]
    chain_id_to: u64,
    nonce: u64,
    receiver: String,
    #[serde(rename = "hasAuto")]
    has_auto: bool,
    #[serde(rename = "executionFee")]
    execution_fee: String,
    flags: String,
    #[serde(rename = "fallbackAddress")]
    fallback_address: String,
    data: String,
    #[serde(rename = "nativeSender")]
    native_sender: String,
    #[serde(rename = "submissionId")]
    submission_id: String,
    #[serde(rename = "cancelId")]
    cancel_id: String,
    #[serde(rename = "refundId")]
    refund_id: String,
}

fn bytes(hex_str: &str) -> Vec<u8> {
    let s = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    if s.is_empty() {
        return Vec::new();
    }
    hex::decode(s).expect("invalid hex in fixture")
}

fn dec(s: &str) -> U256 {
    U256::from_str_radix(s, 10).expect("invalid decimal in fixture")
}

fn fixtures_path() -> PathBuf {
    // crates/bridge-core -> ../../contracts/fixtures/submission_ids.json
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../contracts/fixtures/submission_ids.json")
}

#[test]
fn rust_matches_solidity_for_all_fixtures() {
    let path = fixtures_path();
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "could not read {} ({e}). Run: forge test --match-contract GenFixtures",
            path.display()
        )
    });
    let parsed: Fixtures = serde_json::from_str(&raw).expect("invalid fixtures json");

    assert!(parsed.fixtures.len() >= 5, "expected at least 5 fixtures");

    // The fixture set deliberately contains entries identical in every field but
    // one — `bridgeDomain` for one pair, `bridgeDecimals` for another. If Rust
    // ever stopped folding either into the preimage, the pair would hash the same
    // and the per-fixture assertions below would still pass against a Solidity
    // side that also (wrongly) agreed. Pinning the divergence here makes that
    // regression impossible to miss.
    let mut by_id = std::collections::HashMap::new();
    for f in &parsed.fixtures {
        if let Some(prev) = by_id.insert(&f.submission_id, &f.name) {
            panic!("fixtures '{prev}' and '{}' share a submissionId", f.name);
        }
    }

    for f in &parsed.fixtures {
        let sub = Submission {
            bridge_domain: f.bridge_domain.parse::<B256>().expect("bad bridgeDomain"),
            debridge_id: f.debridge_id.parse::<B256>().expect("bad debridgeId"),
            bridge_decimals: f.bridge_decimals,
            amount: dec(&f.amount),
            chain_id_from: U256::from(f.chain_id_from),
            chain_id_to: U256::from(f.chain_id_to),
            nonce: U256::from(f.nonce),
            receiver: bytes(&f.receiver),
            auto: if f.has_auto {
                Some(AutoParams {
                    execution_fee: dec(&f.execution_fee),
                    flags: dec(&f.flags),
                    fallback_address: bytes(&f.fallback_address),
                    data: bytes(&f.data),
                    native_sender: bytes(&f.native_sender),
                })
            } else {
                None
            },
        };

        let expected = f.submission_id.parse::<B256>().expect("bad submissionId");
        let got = sub.compute_id();
        assert_eq!(
            got, expected,
            "submissionId mismatch for fixture '{}': rust={got:#x} solidity={expected:#x}",
            f.name
        );

        // The refund path's two attestation domains must agree with Solidity too,
        // or a validator's cancel/refund signature would never verify on-chain.
        let expected_cancel = f.cancel_id.parse::<B256>().expect("bad cancelId");
        let got_cancel = bridge_core::cancel_id(got);
        assert_eq!(
            got_cancel, expected_cancel,
            "cancelId mismatch for fixture '{}': rust={got_cancel:#x} solidity={expected_cancel:#x}",
            f.name
        );

        let expected_refund = f.refund_id.parse::<B256>().expect("bad refundId");
        let got_refund = bridge_core::refund_id(got);
        assert_eq!(
            got_refund, expected_refund,
            "refundId mismatch for fixture '{}': rust={got_refund:#x} solidity={expected_refund:#x}",
            f.name
        );

        // Domain separation is the whole defence against replaying a transfer
        // signature as a cancel/refund authorisation. Assert the three digests
        // for one submission are pairwise distinct.
        assert_ne!(got_cancel, got, "cancelId collides with its submissionId");
        assert_ne!(got_refund, got, "refundId collides with its submissionId");
        assert_ne!(got_cancel, got_refund, "cancelId collides with refundId");
    }
}
