#!/usr/bin/env bash
# gen5-relayers.sh — run the Solana relayers for the Generation-5 mesh.
#
#   bash scripts/testing/gen5-relayers.sh start
#   bash scripts/testing/gen5-relayers.sh stop
#   bash scripts/testing/gen5-relayers.sh status
#
# WHY TWO. Solana `Sent` events are signed ONLY by relayers — the EVM validators
# never scan Solana — so a threshold-2 gate needs two relayers holding DISTINCT
# validator keys, or Solana->EVM transfers stall one signature short, silently.
# Only ONE carries a `[target]` block: that is the EVM->Solana claim submitter
# (the keeper role). A second submitter would not be unsafe — every submit
# re-reads the on-chain ["executed", id] marker first, so the loser of a race
# lands nothing — it would just burn SOL losing races.
#
# The program id is DERIVED from .solana/gen5/program-keypair.json rather than
# read from solana-devnet.config.local, which still names the Gen-4 program. One
# source of truth, and no need to edit a file holding live keys.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

# shellcheck disable=SC1090
source scripts/solana-devnet.config.local
# shellcheck disable=SC1090
source scripts/gen5.config.local

# Run-dir files are PARSED, not sourced, and only from a dir this user owns
# (audit round 5, LOW: the old fixed /tmp default could be pre-created by any
# local user). See _rundir.sh.
source "scripts/testing/_rundir.sh"
RUN_DIR="${RUN_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/selendra-bridge/gen5}"
BIN="$ROOT/crates/solana-relayer/target/debug/solana-relayer"
PROGRAM_KP=.solana/gen5/program-keypair.json
PID=$(solana-keygen pubkey "$PROGRAM_KP")
STORE_URL="http://${BIND_HOST:-127.0.0.1}:${STORE_PORT:-8080}"

case "${1:-status}" in
start)
  [[ -x "$BIN" ]] || cargo build --manifest-path crates/solana-relayer/Cargo.toml --bin solana-relayer
  mkdir -p "$RUN_DIR"
  rundir_trusted "$RUN_DIR" || exit 1

  # Scoped sig-store credential: a relayer signs, so `Sign` is all it needs.
  [[ -f "$RUN_DIR/tokens.env" ]] && { load_env_file "$RUN_DIR/tokens.env" || exit 1; }

  # The EVM gates the scanner cross-checks before signing (H-2, audit
  # 2026-09-16). The submissionId does not commit to the asset's scale, so a
  # Solana->EVM transfer is signed only once the relayer has read the DESTINATION
  # gate and seen it agree on the bridge decimals. It fails CLOSED, so a chain
  # missing here is a chain nothing bridges to — which is why a missing
  # addresses.env is an error and not a shrug.
  ADDR_ENV="$RUN_DIR/addresses.env"
  [[ -f "$ADDR_ENV" ]] || {
    echo "  !! $ADDR_ENV not found — run scripts/run.sh first; without the gate" >&2
    echo "     addresses the relayers can verify nothing and would sign nothing." >&2
    exit 1
  }
  load_env_file "$ADDR_ENV" || exit 1

  # The RPC URLs carry the Alchemy key, so they reach the process through the
  # environment like the signing keys do — never inlined into a world-readable
  # TOML in /tmp.
  # A scale read at the chain tip can be reorged away, so the reader refuses a
  # zero buffer outright — clamp rather than emit a config it will reject.
  EVM_CONF="${REFUND_BLOCK_CONFIRMATION:-6}"
  (( EVM_CONF >= 1 )) || EVM_CONF=1
  EVM_PEERS=()
  for _entry in "${CHAINS[@]}"; do
    IFS='|' read -r _cid _nm _rpc _ <<<"$_entry"
    _cid="${_cid// /}"; _rpc="${_rpc// /}"
    _gate_var="CHAIN_${_cid}_GATE"
    _gate="${!_gate_var:-}"
    [[ -n "$_gate" ]] || { echo "  !! $_gate_var unset in $ADDR_ENV" >&2; exit 1; }
    export "EVM_RPC_$_cid=$_rpc"
    EVM_PEERS+=("$_cid|$_gate")
  done

  n=0
  for key in "${VALIDATOR_KEYS[@]}"; do
    n=$((n + 1))
    cfg="$RUN_DIR/solana-relayer-$n.toml"
    # The key reaches the process through the environment, never the file: this
    # TOML is world-readable in /tmp and an inline private_key would leak it.
    export "SOLANA_VALIDATOR_KEY_$n=$key"

    {
      echo "# GENERATED by scripts/testing/gen5-relayers.sh — do not edit."
      echo "[source]"
      echo "chain_id = $SOLANA_CHAIN_ID"
      echo "rpc = \"$SOLANA_RPC\""
      echo "program_id = \"$PID\""
      # finalized is the analogue of the EVM block_confirmation: signing a Sent
      # that a fork discards would pay out against a deposit that never settles.
      echo "commitment = \"finalized\""
      echo "poll_interval_ms = 4000"
      echo "max_batch = 100"
      echo "state_file = \"$RUN_DIR/solana-relayer-$n-state.json\""
      echo
      echo "[signer]"
      echo "private_key_env = \"SOLANA_VALIDATOR_KEY_$n\""
      echo
      echo "[store]"
      echo "url = \"$STORE_URL\""
      echo "token_env = \"SIG_STORE_VALIDATOR_TOKEN\""
      # One reader per EVM chain a Solana-origin transfer can land on — see the
      # EVM_PEERS comment above. block_confirmation is the same reorg argument as
      # the refund attester's: a scale read at the tip can be reorged away.
      for _peer in "${EVM_PEERS[@]}"; do
        IFS='|' read -r _cid _gate <<<"$_peer"
        echo
        echo "[[evm_destinations]]"
        echo "chain_id = $_cid"
        echo "gate = \"$_gate\""
        echo "rpc_env = \"EVM_RPC_$_cid\""
        echo "block_confirmation = $EVM_CONF"
      done
      # Exactly one deliverer — see the header.
      if [[ "$n" == "1" ]]; then
        echo
        echo "[target]"
        echo "payer_keypair = \"$ROOT/$SOLANA_PAYER_KEYPAIR\""
        echo "poll_interval_ms = 4000"
      fi
    } > "$cfg"

    setsid bash -c "exec $BIN $cfg" >"$RUN_DIR/solana-relayer-$n.log" 2>&1 </dev/null & disown || true
    echo "  relayer $n -> $cfg  (log $RUN_DIR/solana-relayer-$n.log)$([[ $n == 1 ]] && echo '  [delivers EVM->Solana]')"
  done

  sleep 8
  up=$(pgrep -fc "solana-relayer $RUN_DIR" 2>/dev/null || echo 0)
  echo "  $up relayer process(es) up against program $PID"
  for l in "$RUN_DIR"/solana-relayer-*.log; do
    grep -qiE "error|panic" "$l" && { echo "  !! errors in $l:"; grep -iE "error|panic" "$l" | head -3; }
  done
  ;;

stop)
  pkill -f "solana-relayer $RUN_DIR" 2>/dev/null && echo "  stopped" || echo "  none running"
  ;;

status)
  echo "program: $PID"
  pgrep -af "solana-relayer $RUN_DIR" | sed 's/^/  /' || echo "  no relayers running"
  for l in "$RUN_DIR"/solana-relayer-*.log; do
    [[ -f "$l" ]] || continue
    echo "--- $(basename "$l") ---"; tail -3 "$l"
  done
  ;;

*) echo "usage: $0 {start|stop|status}" >&2; exit 1 ;;
esac
